// File Tags for Purchase Parts and Projects
export const FILE_TAGS = [
  "Others",
  "Add New",
  "(Black Skin/Scale removal)",
  "(Inside dimension)",
  "(machine name) Outfitting",
  "(Remove black Skin)",
  "(Scale Removal)",
  "*Circuit diagram arrangement",
  "01_ Fastener parts",
  "02_ Purchased parts",
  "03_Piping parts",
  "3-Point Welding",
  "A is only difference from (DWG no.)",
  "Accurately perpendicular to Datum surface A",
  "Achieve dimension by both side grinding and pass to assembly",
  "Additional Length",
  "Additional proccess from Purchased Parts",
  "Additional process when its assemble",
  "Adjust in site and machine",
  "Adjustment at the time of assembly",
  "Adjustment Screw",
  "Adjustment Table",
  "AF Type Disc Brake",
  "After installation of electrical parts, these parts will be removed",
  "After partition",
  "After plating dimension",
  "After polishing finish",
  "Air Cylinder",
  "Air Equipment Arrangement",
  "Air Filter",
  "Air Hole Standard Note",
  "Air Tank",
  "Air Vent",
  "Aligning Conveyor Assy",
  "Aligning End Surface",
  "Aligning Machine",
  "Aligning Roll Assy",
  "Aligning Roller",
  "Aligning Stopper Stand",
  "Aligning the Inlet-side Pickup",
  "All Circumference C1 (Both Sides)",
  "All corner chamfered C1 even without any notes on drawing",
  "All Threaded Bolt",
  "All View Drawing",
  "Already manufactured parts will be used",
  "Alumite Treatment",
  "Anchor",
  "Angle",
  "Angle Bar(Equal)",
  "Angle Bar(Unequal)",
  "Angle for Anchoring",
  "Angular Contact Ball Bearing",
  "Annealing after rough machining",
  "Anti-Rotation Plate",
  "Anti-vibration sheet (Hanenite)",
  "Aperture type distributor",
  "Apply existing jack sets(Inc. bolts)",
  "Apply fillet welding for other joint if there are no special notes.",
  "Apron",
  "Archgrip",
  "Arm",
  "Arm Assembly",
  "Arm Guide",
  "Arm Plate",
  "Arm Ring",
  "Arm Shaft",
  "Arrow View",
  "Assembling Jig Rod",
  "Assembly Drawing",
  "Attachment",
  "Attachment Mount",
  "Auxiliary contact",
  "Auxiliary Skid",
  "Axis",
  "Back Bar",
  "Back Bar Holder",
  "Back Bar Pressure Plate",
  "Back Side (Other Side)",
  "Back Side Drying Furnace (Conveyor)",
  "Back Side Drying Furnace Exit Side (Roller Table)",
  "Back Side Painting Bush Exit Side (Roller Table)",
  "Back Support",
  "Backing Plate",
  "Balance Beam",
  "Balance Weight",
  "Ball Bearing Unit",
  "Ball Screw Cover",
  "Ball Valve",
  "Base",
  "Base Block",
  "Base Bracket",
  "Base Flange",
  "Base Frame",
  "Base Holder",
  "Base Plate",
  "Base Ring",
  "Basic Collar",
  "Beam",
  "Beam Axis",
  "Bearing",
  "Bearing Axis",
  "Bearing Block",
  "Bearing Box",
  "Bearing Cap",
  "Bearing Case",
  "Bearing Holder",
  "Bearing Housing",
  "Bearing Nut",
  "Bearing Pin",
  "Bearing Plate",
  "Bearing Retainer",
  "Bearing Stand",
  "Bearing Unit Bracket",
  "Bearing Washer",
  "Bed",
  "Bed Assembly",
  "Before plating dimension",
  "Bellows",
  "Belt",
  "Belt Cover",
  "Belt Pulley",
  "Bevel Buddybox",
  "Bevel Driven Gear",
  "Bichrome Plating Installation",
  "Bite Fittings Elbow",
  "Bite Fittings Nipple",
  "Bite Holder",
  "BKAL Bundling Machine(Width Determining Device)",
  "BKLF Bundling Machine(Width Determining Device)",
  "BKMU Bundling Machine(Width Determining Device)",
  "BKPS Bundling Machine(Width Determining Device)",
  "BKSF Bundling Machine(Width Determining Device)",
  "BKWD Bundling Machine(Width Determining Device)",
  "Black",
  "Blade Edge must be wire cut",
  "Blade mounting base",
  "Blade Presser",
  "Block",
  "Block Guide",
  "Block L",
  "Block R",
  "Blocking Flange",
  "BMAL Back Side Painting Bush Exit Side (Roller Table)",
  "BMAL Bead Remover (Cutter Stand)",
  "BMAL Bundling Machine (Alignment)",
  "BMLF Bundling Machine (Transfer Table)",
  "BMLF Bundling Machine(Inclined Skid)",
  "BMLF Bundling Machine(Lifter)",
  "BMPS Bundling Machine(Piler)",
  "BMSF Bundling Machine(Pusher)",
  "BMTR Bundling Machine (Alignment)",
  "BMWD Bundling Machine(Pusher)",
  "BMWD Bundling Machine(Slide Fork)",
  "BMWD Bundling Machine(Width Determining Device)",
  "Board Charge",
  "Body Bed",
  "Body Frame",
  "Body Upper Protective Cover",
  "Bolt",
  "Bolt & Washer",
  "Bolt Shaft",
  "Bored Crank Handle",
  "Boss",
  "Both Side",
  "Bottom Bracket",
  "Bottom Cutter Rotating",
  "Bottom Guide",
  "Bottom Lift Base",
  "Bottom Limit SW Dwg.",
  "Bottom Roll Holder",
  "Bottom Roll Plate",
  "Bottom Roller",
  "Bottom Shoe",
  "Box Frame",
  "Brace",
  "Bracket",
  "Bracket Case",
  "Bracket Cover",
  "Bracket for Fix side ( For cableveyor)",
  "Bracket for moving side ( For cableveyor)",
  "Brake Sky Pressure Piping Diagram",
  "Break Boss",
  "Buddybox Reducer",
  "Bush",
  "Bush for Locating Pin",
  "By Table (BOM)",
  "By Table (Qty)",
  "Cable Support",
  "Cableveyor Bracket",
  "Cableveyor Layout",
  "Cableveyor Rail",
  "Cableveyor Support",
  "Cableveyor Vertical Partition Plate",
  "Cam",
  "Cam Bracket",
  "Cam Follower",
  "Cam Mtg. Plate",
  "Cam Ring",
  "Cam Roller Pin",
  "Cam Shaft",
  "Can be penetrated",
  "Can be stugger welding",
  "Chain Attachment",
  "Chain Coupling",
  "Chain Cover",
  "Chain Guard",
  "Chain Guard Mfg.",
  "Chain Guard Stay",
  "Chain Guide",
  "Chain Lifter Frame",
  "Chain Rail",
  "Chamfered",
  "Chamfered Enter Side Pickup",
  "Chamfered Exit Side Pickup",
  "Character Height",
  "Check the position of the keyway with the mating part",
  "Checkered Plate",
  "Chemical Anchor Bolt",
  "Chip Saw",
  "Chock",
  "Chock (Fixed Side)",
  "Chock (Moving side)",
  "Chock Piece",
  "Chock Piece Holder",
  "Chrome Plating",
  "Chute",
  "circumferential equipartition",
  "Clamp",
  "Clamp Arm",
  "Clamp Base",
  "Clamp Frame",
  "Clamp Lever",
  "Clamp Mount",
  "Clamp Piece",
  "Clamp Plate",
  "Clamp Shaft",
  "Clamping Plate",
  "Clamping Sleeve",
  "Clasp",
  "Clevis",
  "Clevis Bracket",
  "Clevis Pin",
  "Clip",
  "Close Bracket",
  "Cloud marks area will be additional process(M155x3)",
  "Clutch Lever",
  "Coil Spring",
  "Collar",
  "Collar (for sending)",
  "Collar (for turning)",
  "Collar for Countersunk Urethane",
  "Collet",
  "Column(Post, Stand)",
  "Combination Type Angular Bearing Unit",
  "Common Base",
  "Common parts",
  "Coned Disc Spring",
  "Connecting Bar",
  "Connecting Bolt",
  "Connecting Fitting",
  "Connecting Nut",
  "Connecting Plate",
  "Connecting Rod",
  "Connector",
  "Connector Bite",
  "Consider heat expansion after heat treatment",
  "Consider well for plate cutting",
  "Conveyor Guard",
  "Conveyor Roller",
  "Conveyor Shaft",
  "Conveyor Shaft (Intermediate)",
  "Copper Pipe",
  "Copper Tube",
  "Cored Bar",
  "Corner Rack",
  "Cotter",
  "Counterbore",
  "Coupling",
  "Coupling Cover",
  "Cover",
  "Cover Above",
  "Cover Below",
  "Cover Bracket",
  "Cover Frame",
  "Cover Plate",
  "Cover Stay",
  "Covexing Roll Unit",
  "Cradle",
  "Cradle Carrier Bar",
  "Cross Roller Bearing",
  "Crown",
  "Cup Nut",
  "Cushion",
  "Cushion Plate",
  "Customer Emergency Stop",
  "Customer Supply",
  "Cut Ring",
  "Cut the hatching area and achieve dimension as left drawing for the modification.",
  "Cutter",
  "Cutting Edge",
  "Cutting Tool",
  "Cyclo Speed Reducer With Gearmotor",
  "Cylinder",
  "Cylinder Base",
  "Cylinder Bracket",
  "Cylinder Clevis",
  "Cylinder End Bracket",
  "Cylinder Extension End Bracket",
  "Cylinder Eye",
  "Cylinder Eye Holder",
  "Cylinder Flange",
  "Cylinder Frame",
  "Cylinder Head",
  "Cylinder Mounting",
  "Cylinder Receiver",
  "Cylinder Rod",
  "Cylinder Support",
  "Cylinder Support Bracket",
  "Cylinder Tip Bracket",
  "Cylinder Top Bracket",
  "Cylinder Tube",
  "Cylindrical Roller Bearing",
  "Damper",
  "Damper Tip Bracket",
  "Deck",
  "Deep Groove Ball Bearing",
  "Deep Socket",
  "Defective Side Bracket",
  "Defective Side Skid",
  "Deformed Nipple/Not uniformed Nipple",
  "Depth",
  "Design Value",
  "Detail Drawing",
  "Detection Ring",
  "Detent Bolt",
  "Detent Pin",
  "Develop Drawing",
  "DF head selector switch",
  "DFAI Bundling Machine(Width Determining Device)",
  "DFAI Cleaning Entry Side (Roller Table)",
  "DFAI Cleaning Exit Side (Roller Table)",
  "DFAI Cooling (Conveyor)",
  "DFAI Cooling Exit Side (Roller Table)",
  "DFAI Debundling Machine",
  "DFAI Debundling Machine Exit Side (Conveyor)",
  "DFAI Dedimpler&Facer(Air Blow)",
  "DFBD Dedimpler&Facer(Air Blow)",
  "DFCL Dedimpler&Facer(Air Blow)",
  "DFEG Dedimpler&Facer(Entry Guide)",
  "DFFH Dedimpler&Facer(Entry Guide)",
  "DFMU Dedimpler&Facer(Main Unit)",
  "DFPS Dedimpler&Facer(Main Unit)",
  "DFRD Dedimpler&Facer(Pusher)",
  "DFSL Dedimpler&Facer(Pusher)",
  "Dial Ring",
  "Die Side Bush",
  "Die Slide Bush",
  "Digital Position Indicator",
  "Disc Cutter",
  "Disk Brake",
  "Disk Brake Bracket",
  "Disk Plate",
  "Disposal Base for Machine Grinding",
  "Distribution Gear Cover",
  "Distributor",
  "Dividing after machining (standard notes)",
  "DK Tube",
  "Do not paint anti-rust",
  "Do not paint on the installation surface",
  "Do not paint the surface of installation side",
  "Do not paint with rust prevention (Sir. Tanaka)",
  "Do not remove distortion (press correction, etc.) after tempering",
  "Dog Bracket",
  "Dogg",
  "Dogg Base",
  "Dogg Holder",
  "Double Clevis Pivot Bracket",
  "Double dot chain line hard chromate",
  "Drill at assembly",
  "Drill Hole",
  "Drill Thru",
  "Drill thru the pilot hole",
  "Drive Base",
  "Drive Collar",
  "Drive Side",
  "Drive Side Chock",
  "Drive Side Frame",
  "Drive Sprocket",
  "Driving Unit",
  "Drum Segment",
  "Drum Sleeve",
  "Dry Bearing",
  "Dry Bush",
  "DS Side Piping Dwg",
  "DS Side Wiring Dwg",
  "DU Bush",
  "Duct",
  "Dummy - Block",
  "Dust Seal",
  "Each dimension is the value of pre-edge processing",
  "Each portion of ※, pay higher attention of perpendicularity and parallelly",
  "Earth Plate",
  "Eccentricity",
  "Eccentricity Cam",
  "Edge",
  "Elbow",
  "Elbow Union",
  "Electrical Wiring for Machine",
  "Electro-pneumatic Regulator",
  "EMER-FLEX Coupling",
  "Emergency Stop",
  "Encoder Flange",
  "Encoder Guard",
  "Encoder Housing",
  "Encoder Liner",
  "Encoder Mounting Bracket",
  "Encoder Mounting Flange",
  "Encoder Mounting Plate",
  "End Cap",
  "End Plate",
  "End Plate (for sending)",
  "End Plate (for turning)",
  "Enlarge View",
  "Entry Guide Soluble Piping Diagram",
  "Entry Main Frame",
  "Entry Side Bracket",
  "Entry Side Clamp Frame",
  "Entry Side Guide Plate",
  "Entry Side Sensor Mounting Figure",
  "Equally divided (notes on drawing)",
  "Evenly divided into equal circumferences",
  "Excess must have when forged, One side should be 8~10mm",
  "Exit Bracket",
  "Exit Main Frame",
  "Exit Side Guide Plate",
  "Exit Side Guide Roll",
  "Exit Side Mounting Figure",
  "Exit Stopper",
  "Exit Table",
  "Extension Block",
  "F Joint",
  "Face Plate",
  "Field welding after fixing shaft with link",
  "Field welding on all joint portion",
  "Fine U Nut",
  "Finger Needle",
  "Fit Bore Sprocket",
  "Fitting parts: CP251K2A01",
  "Fitting Plug",
  "Fix Entry Side",
  "Fix Exit Side",
  "Fix Type Boring Unit",
  "Fixed Body Base",
  "Fixed Rail",
  "Fixing Screw",
  "Flange",
  "Flange Mounting Plate",
  "Flange Type Unit",
  "Flanged Bushing",
  "Flap",
  "Flapper",
  "Flat Head Screw with Key",
  "Flex Cover",
  "Flex Guide",
  "Floating Frame",
  "Floating Joint",
  "Floor Plate",
  "Flow",
  "Fog Manifold",
  "Fog Nozzle",
  "For Anchoring",
  "For Chip conveyor control box",
  "For Hanging",
  "For Leveling",
  "For motor adjustment",
  "For Removal",
  "For Site Welding",
  "Frame Bracket",
  "Frame Connector",
  "Frame Cover",
  "Frame Support",
  "Freno Link Bolt",
  "Freno Ring",
  "Friction Pad",
  "Front Cover",
  "Front Support",
  "FSBT Exit Side of Piling Machine (Roller Table)",
  "FSMR Forming and Sizing Machine (Bed)",
  "FSMR Forming and Sizing Machine (Entry Guide)",
  "FSMR Forming and Sizing Machine (Ironing Roll Stand)",
  "FSMR Forming and Sizing Machine (Measuring Roll)",
  "Fulcrum Pin",
  "Full thread / All screw",
  "Gas Cut",
  "Gauge Base",
  "Gauge Cover",
  "Gauge Holder",
  "Gauge Plate",
  "Gauge Valve",
  "GC Coupling",
  "Gear",
  "Gear (Body Crank Shaft)",
  "Gear (for turning)",
  "Gear (Intermediate Crank Shaft)",
  "Gear (Intermediate Shaft & Transport Axis)",
  "Gear (Middle Shaft)",
  "Gear Case",
  "Gear Coupling",
  "Gear Cover",
  "Gear Guide",
  "Gear House",
  "Gear Shaft",
  "Gearbox",
  "Gearbox Cover",
  "Gearmotor",
  "General Anchor Plan",
  "Girder",
  "Glove Valve",
  "Good",
  "Good Side Bracket",
  "Good Side Skid",
  "Grease Nipple",
  "Grease Pan",
  "Grease Piping Diagram",
  "Greasing Case",
  "Grind / Buff finish #300 notes",
  "Grind and finish as A dimension when its assemble",
  "Grinding after coating",
  "Grip",
  "Grommet",
  "GS-shaped Bearing Ring",
  "Guard Plate",
  "Guard Stay",
  "Guide",
  "Guide Bar",
  "Guide Base",
  "Guide Block",
  "Guide Box",
  "Guide Bracket",
  "Guide Holder",
  "Guide Line",
  "Guide Plate",
  "Guide Plate Holder",
  "Guide Rail",
  "Guide Rod",
  "Guide Roll",
  "Guide Roller",
  "Guide Shoe",
  "Guide Stopper",
  "Guide Table",
  "Guideline Table",
  "Half Union",
  "Half Washer",
  "Hammer Type Bolt",
  "Hand Wheel",
  "Handle",
  "Hanger",
  "Hanger Bearing",
  "Hanging Bracket",
  "Hanging Hand",
  "Hard Alumite Treatment",
  "Hard Chromating",
  "Hard Lock Nut",
  "Head",
  "Head Case",
  "Head Cover",
  "Head Flange",
  "Head Plate",
  "Helical Power Drive",
  "Hex Bolt",
  "Hex Socket Plug",
  "Hex. Nut",
  "Hexagon Socket Head Plug",
  "High Pitch Chain",
  "Hinge",
  "Hinge Pin",
  "HN1 Naming for Parts",
  "Holder",
  "Holder (for sending)",
  "Holder (for turning)",
  "Holder Arm (inside)",
  "Holder Arm (outside)",
  "Holder Base-L",
  "Holder Bracket",
  "Holder Frame",
  "Holding Bar",
  "Holding Fittings",
  "Holding Plate",
  "Hole Shape, Manufacturer Over Responsibility",
  "Honing",
  "Hook",
  "Hook Clamp",
  "Horizontal Roll Stand",
  "Hose Cap",
  "Hose Clamp",
  "Hose Fitting",
  "Hose Standard Naming",
  "Host Strut",
  "Housing",
  "Hydraulic and Pneumatic Piping Diagram",
  "Hydraulic Connection",
  "Hydraulic Cylinder",
  "Hydraulic Motor",
  "Hydraulic Piping Diagram",
  "Hypoid Motor",
  "Hyponic Gearmotor",
  "Idler Pin",
  "Idler Shaft",
  "Idler Sprocket",
  "IGUS (3050 ZC)(Comb type Cable clamp)",
  "IGUS (56.5) (Separator with Nail)",
  "In front of Air Blow",
  "Inclined Skid Assy",
  "Increasing Pressure Valve",
  "Increasing Valve",
  "Index Plunger",
  "Indicator",
  "Indicator Bracket",
  "Indicator Mount",
  "Indicator Safety Cover",
  "Induction hardening",
  "Inductive Sensor",
  "Inlet Guide",
  "Inner Arm",
  "Inner Arm Mounting Plate",
  "Inner Arm Plate",
  "Inner Arm Top Plate",
  "Inner Bead Cutter",
  "Inner Bead Cutter Assy",
  "Inner Collar",
  "Inner Cover",
  "Inner Guide",
  "Inner Pin",
  "Inner Skid",
  "Inner Spacer",
  "Inner Stand",
  "Inner Stand Clamp Assy",
  "Inner Stand Entry Side",
  "Inner Stand Outer Side",
  "Inner Wheel",
  "Inside Stopper",
  "Inspection Conveyor Assy",
  "Install in site",
  "Installation Angle",
  "Installation at the time of assembly",
  "Insulation Spray (thickness 0.3mm)",
  "Insulation Spray(Ceramic coating)",
  "Intermediate Gear Shaft",
  "Intermediate Guide Plate",
  "Intermediate Plate",
  "Intermediate Shaft",
  "Intermediate Unit Base",
  "Intermediate Unit Clamp Portion Assy",
  "Intermediate Unit Frame",
  "Intermediate Unit Frame Cover",
  "Intermediate Unit Gear Box Assy",
  "Intermediate Unit Pipe Holder Assy",
  "Internal buffing process",
  "Invalid Emergency Stop",
  "Inverter Drive Constant Torque Motor",
  "Iron Pipe",
  "Ironing Roll Stand",
  "It is oil pan, pay attention for welding. Sealed welding must be applied.",
  "It must be flat surface",
  "Jack",
  "Jack Base",
  "Jack Bolt",
  "Jack Bracket",
  "Jack Cover",
  "Jack Plate",
  "Jack Rod End",
  "Jack Screw",
  "Jaw Flex Coupling",
  "Jig",
  "Jig for Carriage Encoder",
  "Joint",
  "Joint Bar",
  "Joint Block",
  "Joint Bolt",
  "Joint Holder",
  "Joint Plate",
  "Joint Shaft",
  "Joint Sleeve",
  "Junction Box",
  "Junction Box Frame",
  "Junction box frame no welding notes",
  "Keeper Plate",
  "Key",
  "Key attached surface",
  "Key Corner",
  "Key Groove Details",
  "Key Groove must be Aligned",
  "Key groove should be machine at the center of the tooth",
  "Key Plate",
  "Kick Lever",
  "Kicker",
  "Kicker Collar",
  "Kicker End Plate",
  "Kicker Shaft",
  "Kickout Assy",
  "Knob",
  "Kyoushin Dengyo",
  "L-Type Stand",
  "L S Base",
  "L S Installation Drawing",
  "Labyrinth Cover",
  "Laser cutting is possible",
  "Lead Screw",
  "Lead Screw Nut",
  "Left",
  "Left Side(Hand)",
  "Left Thread",
  "Less than",
  "Leveling Block",
  "Leveling Roll Assy",
  "Lever",
  "Lever Clamp",
  "Lever Holder",
  "Lever Pin",
  "Lever Stopper",
  "Lid",
  "Lift Base",
  "Lifter",
  "Lifter (Round Tube)",
  "Lifter Frame",
  "Lifter Frame Base",
  "Lifter Shaft",
  "Lifting Base Plate",
  "Lifting Frame",
  "Lifting Plate",
  "Lifting Stopper",
  "Light Chamfering",
  "Light Channel Steel",
  "Limit Bracket",
  "Limit Switch",
  "Limit Switch Mounting Bracket",
  "Linear Bush",
  "Linear Guide",
  "Linear Guideway",
  "Linear Scale",
  "Liner",
  "Liner (Start)",
  "Link",
  "Link Ball",
  "Link Bolt",
  "Link Plate",
  "LM Block",
  "LM Bracket",
  "LM Case Unit",
  "LM Guide",
  "LM Guide Bracket",
  "LM Guide Rail",
  "LM Guide with C Cap",
  "LMEG Forming and Sizing Machine(Mill Turks Head Roll Stand)",
  "LMLR Friction Saw Cut off Machine(Clamp Device)",
  "LMLR Friction Saw Cut off Machine(Guide Roll)",
  "LMMU Forming and Sizing Machine(Mill Turks Head Roll Stand)",
  "LMMU Forming and Sizing Machine(Twister Side Roll)",
  "LMOF Friction Saw Cut off Machine(Saw Head)",
  "LMPR Friction Saw Cut off Machine (Clamp Device)",
  "LMPR Friction Saw Cut off Machine (Guide Roll)",
  "LMPR Friction Saw Cut off Machine (Main Bed)",
  "LMPR Friction Saw Cut off Machine (Saw Head)",
  "LMPR Friction Saw Cut off Machine(Carriage Device)",
  "Load Cell",
  "Load Holder",
  "Location Bracket",
  "Lock Base",
  "Lock Bracket",
  "Lock Nut",
  "Lock Pin",
  "Lock Plate",
  "Lock Stand",
  "Loctite",
  "Long Elbow Bite",
  "Long Nipple",
  "Low Pressure Hose",
  "Lower Chock (W.S)",
  "Lower Chock Holder",
  "Lower Frame",
  "Lower Holder",
  "Lower Housing",
  "Lower mechanical stop",
  "Lower Roll Axis",
  "Lower Roll Holder",
  "Lower Tool & Clamp Feed (Entry Side) Assy",
  "Lower Tool & Clamp Feed (Outlet Side) Assy",
  "Lubrication Equipment Assy",
  "Lubrication Unit",
  "Lubricator",
  "Machine after welding",
  "Machine Before Welding",
  "Machining from both side",
  "Machining, gear cutting, etc. Main finishing",
  "Main Assy",
  "Main Base",
  "Main Block",
  "Main Block Base",
  "Main Bolt",
  "Main Cover",
  "Main Disk",
  "Main Frame Assy",
  "Main Plate",
  "Main Shaft",
  "Main Side Plate",
  "Main Stand Grease Piping",
  "Main Stand Hydraulic Piping",
  "Main Stand Main Piping",
  "Main Unit Crunk Portion Assy",
  "Main Unit Transfer Gear Box Assy",
  "Make base/prepare for Insulation Spray",
  "Male and Female Socket",
  "Mandrel Assy",
  "Manifold Base",
  "Manifold Block",
  "Manifold Block Base",
  "Manifold Bracket",
  "Manometer",
  "Manual Lock Device",
  "Material SUS304",
  "Maximum Stopper",
  "Maximum tube length",
  "MCCL Loading & Storaging (Conveyor)",
  "MCHE Friction Saw Cut off Machine(Saw Head)",
  "MCHE Front Drying Furnace (Conveyor)",
  "MCHE Front Drying Furnace Entry Side (Roller Table)",
  "MCHE Front Drying Furnace Exit Side (Roller Table)",
  "MCHE Front Side of Filing Machine (Conveyor)",
  "Measure shaft diameter and refer bearing inspection data for the ditermination of size",
  "Measure the dimension during assembly and machine",
  "Measuring",
  "Measuring Roll",
  "Measuring Roll Stand",
  "Measuring Roll Stand Assy",
  "Measuring Stand Assy",
  "Mechanical Lock Device Assy",
  "Mechanical Lock Device Assy (With Centering)",
  "Metal",
  "Metal Holder",
  "Metal Holder Cover",
  "Metal Ring",
  "Middle",
  "Middle Collar",
  "Middle Shaft",
  "Mill Stand Assy",
  "Milling Chuck",
  "Minimal (Radius)",
  "Minimum Bending Radius",
  "Minimum Stopper",
  "Mirror finish",
  "Miter Gear",
  "MMX type simple lubricant motor pump",
  "Mobile Unit Locking Device Assy",
  "Modifying Procedures",
  "Motor",
  "Motor Base",
  "Motor Bracket",
  "Motor Cover",
  "Motor Cradle",
  "Motor Liner",
  "Motor Mount",
  "Motor Mounting Plate",
  "Motor Plate",
  "Motor Plate (Base)",
  "Mount",
  "Mount Bracket",
  "Mounting Angle",
  "Mounting Bracket",
  "Mounting Plate",
  "Mounting Position of Motor Base",
  "Moving Body Base",
  "Muffler",
  "Must be accurate parallelly to the datum A",
  "N.S. Cover",
  "N.S. Mount",
  "N.S. Mounting Arm",
  "Name Plate",
  "Necessary qty for each machine",
  "Necessary quantities for each machines, BD-8 FP-8 x2Units",
  "Needle",
  "Needle Bearing",
  "Negic Bracket",
  "Negic Rail",
  "NG / Impossible",
  "Nipple",
  "No need to paint on this surface due to installation",
  "No Need To Touch Up Paint",
  "No Paint",
  "No weld",
  "No Welding",
  "No welding bead appear on this surface",
  "No welding bead protruding due to mounting surface.",
  "No welding inside",
  "Normalizing",
  "Not used(Send to site)",
  "Notch",
  "Notch Equipment",
  "Nozzle",
  "Nozzle Base",
  "Nozzle Plate",
  "Nut",
  "Nut Bracket",
  "Nut Case",
  "Nut for Jack",
  "Nut Holder",
  "Nut Plate",
  "O Ring",
  "Offset Handwheel",
  "Offset Clamp",
  "Offset Crank Handle",
  "Oil Gauge",
  "Oil Groove Detail",
  "Oil Pan",
  "Oil Seal",
  "Oil Seal Cover",
  "Oiles",
  "Only for Hand rail",
  "Only the groove is painted red",
  "Opening & Closing Device Assy",
  "Operating Side Chock",
  "Operating Side Frame",
  "Opposite Worm Shaft DW28180N01",
  "Outer Arm",
  "Outer Arm Shaft",
  "Outer Arm Start Shaft",
  "Outer Arm Support Pin",
  "Outer Collar",
  "Outer Guide",
  "Outer Peripheral Surface Knurled",
  "Outer Race",
  "Outer Ring",
  "Outer Skid",
  "Outer Spacer",
  "Outside Stopper",
  "Oval Grip Lever",
  "Over run switch",
  "Packing",
  "Pad",
  "Paint all",
  "Parallel Key",
  "Parallel Key (Both Side Flat)",
  "Parallel Key (Both Side Round)",
  "Parallel Key (One Side Round)",
  "Part",
  "Part , Simultaneous machining",
  "Part (?) detail drawing",
  "Part(Upper and lower) Laser Hardening Hardness HRC50up",
  "Partition after finish of component(Separate the parts after Machining Finished)",
  "Partition Plate",
  "Parts divided into two (standard notes)",
  "Parts Drawing",
  "Parts Name",
  "Pattying at hatching area after tightening of entry",
  "Pay attention to the thickness of drilling area during piercing",
  "Pickup Holder",
  "Pickup Level",
  "Pickup Stand",
  "Pillow Block",
  "Pillow Type Bearing Unit",
  "Pilot Check Valve",
  "Pilot hole cannot be penetrated",
  "Pin",
  "Pin Bracket",
  "Pin Hole",
  "Pinch Roll",
  "Pinch Roll Assy",
  "Pinch Roll Bracket",
  "Pinch Roll Electric Diagram (Junction Box)",
  "Pinch Roll Electric Diagram (Sensor)",
  "Pinch Roll L S Installation Drawing",
  "Pinion",
  "Pinion Cover",
  "Pipe",
  "Pipe (Start)",
  "Pipe Anchor - Block",
  "Pipe Band",
  "Pipe Clamp",
  "Pipe Cleaner Assy",
  "Pipe Fittings",
  "Pipe Presser Assy",
  "Pipe Receiver",
  "Pipe Transport Chain Assy",
  "Piping",
  "Piping Along Support",
  "Piping Cover",
  "Piping TN & SD",
  "Piston",
  "Piston Rod",
  "Pitch Determined Device Assy",
  "Pre-Assy Ring / Assembled Ring",
  "Precision carbon steel pipe",
  "Presser Bracket",
  "Presser Footer",
  "Presser Plate",
  "Pressure Switch",
  "Previous Construction No.",
  "Pro Cut Endmill",
  "Process from back side",
  "Process from back surface",
  "Process from both side",
  "Process from both surface",
  "Process needed bolt",
  "Process together with (DWG. No.)",
  "Process with other side",
  "Processed also on the other side",
  "Processed from standard products",
  "Processed on the same plane with {FYF}",
  "Processing During Assembly (Not for Piping)",
  "Protective Hardware",
  "Proximity Bracket",
  "Proximity Dogg",
  "Proximity Sensor",
  "Proximity Sensor Rail (Maker: Negic Rail)",
  "Proximity Switch Bracket",
  "Pull Out Pinch Roll Assy",
  "Pull Rod",
  "Pulley",
  "Pulley (driven side)",
  "Pulley Cover",
  "Pulley Mounting Plate",
  "Pulley Shaft",
  "Pulling Pin",
  "Pully blank outside diameter",
  "Pusher Assy",
  "Pusher Block",
  "Quick Exhaust Valve",
  "Quick Test",
  "Rack",
  "Rack Holder",
  "Radius Relief",
  "Rail",
  "Rail Base",
  "Rail Clamp",
  "Rail Cover",
  "Rail Fixing Bracket",
  "Rail for the Block",
  "Rail Lift Device Assy",
  "Rail Nut",
  "Rail Trestle",
  "Ratchet Handle",
  "RCHE Milling Cut Off Machine (Guide Roll)",
  "RCHE Milling Cut Off Machine (Main Frame)",
  "Re-Polishing after all machining finished",
  "Rear Arrange Common Equipment",
  "Rear Cover",
  "Rear Frame",
  "Reclassification Truck",
  "Recognition Label",
  "Red",
  "Reducing Nipple",
  "Reducing Tee",
  "Reem/Reeming",
  "Reference",
  "Reference center",
  "Reference plane",
  "Reference Surface",
  "Regulator",
  "Reinforced Plate",
  "Relay Box Layout",
  "Relay Box Mount",
  "Relay Shaft",
  "Relief Nipple",
  "Relief valve is provided for pressure relief in the line when tube hits the paddle",
  "Removable Roll Base Assy",
  "Remove Hatching area",
  "Remove scale",
  "Remover Base",
  "Remover distorsion after all processing",
  "Rest Pad",
  "Retention Bracket",
  "Revolving Grip",
  "RF Pitch Chain",
  "Rib Plate",
  "Right",
  "Right angle to the keyway",
  "Right C-Channel",
  "Right Side(hand)",
  "Right Thread",
  "Rigid vinyl chloride tube",
  "Ring",
  "Ring Elbow",
  "Ring Joint",
  "Ring Plate",
  "Rise And Fall Bar",
  "Rise And Fall Cam",
  "Rise And Fall Plate",
  "Rod",
  "Rod Cover",
  "Rod End",
  "Rod Fixed Bracket",
  "Rod Flange",
  "Rod Holder",
  "Rodless Cylinder",
  "Roll",
  "Roll Adjusting Assy",
  "Roll Assy",
  "Roll Block",
  "Roll Cassette (Horizontal)",
  "Roll Cassette (Vertical)",
  "Roll Exchange",
  "Roll for Housing",
  "Roll Holder",
  "Roll Lift Assy",
  "Roll Plate",
  "Roll Shaft Measuring Jig",
  "Roll Sleeve",
  "Roller",
  "Roller Arm",
  "Roller Axis",
  "Roller Bracket",
  "Roller Bracket Stand",
  "Roller Chain",
  "Roller Collar",
  "Roller Follower",
  "Roller Frame",
  "Roller Support",
  "Rotary Grip",
  "Rotary Joint",
  "Rotary Joint Assy",
  "Rotate Grip",
  "Rotating Plate",
  "Rotation Stopper-Holder",
  "Rough 5mm on one side, leaving a finishing allowance",
  "Round Aluminum Handle",
  "Round Bar Pull",
  "RS Chain",
  "RS Chain(With Attachement)",
  "RS Lambda Chain",
  "RS Roller Chain",
  "RTKO Milling Cut Off Machine (Main Frame)",
  "RTKS Milling Cut Off Machine (Main Frame)",
  "RTKS Milling Cut Off Machine (Out Fitting)",
  "RTMU Milling Cut Off Machine(Accelerator)",
  "RTMU Milling Cut Off Machine(Carriage Device)",
  "RTW",
  "Rubber Hose",
  "Rubber hose (including both ends -- --)",
  "Rubber Pad",
  "Rubber Seal",
  "Rubber Stopper",
  "S1000 Type Stopper",
  "Safety Cover",
  "Safety Cover Assy Drawing",
  "Safety Tension Lever",
  "Saw Cover",
  "Saw Cover Assy",
  "Saw Cover Plate Assy",
  "Saw Drive Assy",
  "Saw Feed Lock Assy",
  "Saw Head Assy",
  "Scale",
  "Scale Color Red",
  "Scale Holder",
  "Scale Number",
  "Scale Parts",
  "Scale Pitch 0.3mm",
  "Scale Plate",
  "Scale Width",
  "SCCA Milling Cut Off Machine(Carriage Device)",
  "SCCA Piling Machine (Aligning)",
  "SCCA Piling Machine (Cradle Lifter)",
  "SCCA Piling Machine (Fork)",
  "SCCA Piling Machine (Main Frame)",
  "SCCA Piling Machine (Piece Counting Machine)",
  "SCCA Piling Machine (Pipe End Pusher)",
  "SCCA Piling Machine (Pusher)",
  "SCCA Product Storage (Conveyor)",
  "SCCA Rotary Disc Cut Off Machine (Head )",
  "SCGR Rotary Disc Cut Off Machine (Tool)",
  "SCGR Run Out Table (Fitting)",
  "SCGR Run Out Table (Inclined Skid)",
  "SCGR Run Out Table (Kick Out Device)",
  "SCGR Run Out Table (Main Unit)",
  "Scraper",
  "Screw",
  "Screw Bearing",
  "Screw Bushing",
  "Screw Cover",
  "Screw Down Balance Assy",
  "Screw Down Device Assy",
  "Screw Flange",
  "Screw Gear",
  "Screw Jack Bracket",
  "Screw Mounting Seat",
  "Screw Nut",
  "Screw Rail",
  "Screw Up Device Assy",
  "Scribe Line",
  "SD Fit Bore Sprocket",
  "Seal Case",
  "Seal Cover",
  "Seal Plate",
  "Seal Plate Assy",
  "Seal Ring",
  "Sealed Welding",
  "Seat",
  "Section View(Cut Section)",
  "See drawing",
  "Self-Aligning Roller Bearing",
  "Sensor Bracket",
  "Sensor Cover",
  "Sensor Dogg",
  "Sensor Dogg Shaft",
  "Sensor Holder",
  "Sensor Layout",
  "Sensor Liner",
  "Sensor Mounting Bracket",
  "Sensor Mounting Part",
  "Sensor Plate",
  "Sensor Post",
  "Sensor Rail",
  "Sensor Stand",
  "Separate Color",
  "Separator (inside)",
  "Separator (outside)",
  "Set",
  "Set Collar",
  "Set Plate",
  "Set Pointer",
  "Set Screw",
  "Shaft",
  "Shaft (below)",
  "Shaft (for sending)",
  "Shaft (for turning)",
  "Shaft (Motor)",
  "Shaft (Top)",
  "Shaft Bracket",
  "Shaft End",
  "Shaft End Cover",
  "Shaft End Plate",
  "Shaft for Intermediate Guide",
  "Shaft Holder",
  "Shaft Mounting Plate",
  "Shape Change",
  "Shape cut",
  "Shear Cylinder Assy",
  "Shear Pin",
  "Shift Base",
  "Shifter Arm",
  "Shim",
  "Shim Ring",
  "Shock Absorber",
  "Shock Damper",
  "Shoe",
  "Shoot",
  "Shore A90",
  "Shut-off Valve",
  "Side Clamp Plate",
  "Side Frame",
  "Side Guide",
  "Side Guide Roll",
  "Side Limit SW Assy",
  "Side Plate",
  "Side Roll",
  "Side Roll (Entry Side) Assy",
  "Side Roll (Outlet Side) Assy",
  "Side Roll Drive Assy",
  "Side Roll Drive Device",
  "Side Roll Scale Plate",
  "Side Roll Stand",
  "Side Roll Yoke Assy",
  "Side Roller",
  "Side Roller Bracket",
  "Side Yoke Assy",
  "Side Yoke Screw Jack Assy",
  "Side York",
  "Sigma Servomotor",
  "Silicon Varnish Glass Tube",
  "Simultaneous polishing with SB55116N01",
  "Size Stopper Adjustment Mechanism",
  "Sizing Stopper",
  "Sizing Stopper Assy",
  "Skid",
  "Skid Arm",
  "Skid Arm Support Pin",
  "Skid Assy",
  "Skid Base",
  "Skid Frame",
  "Skid Stand",
  "Sleeve",
  "Slide Base",
  "Slide Block",
  "Slide Bracket",
  "Slide Bush",
  "Slide Connector",
  "Slide Device Assy",
  "Slide Flange",
  "Slide Fork",
  "Slide Fork Assy",
  "Slide Frame",
  "Slide Guide",
  "Slide Guide Assy",
  "Slide Key",
  "Slide Plate",
  "Slide Pointer",
  "Slide Ring",
  "Slide Seal",
  "Slide Yoke",
  "Sliding Frame Assy",
  "Sling (for side)",
  "Slip Key",
  "Slippers Ring",
  "Slit Collar",
  "Slot / Long Hole",
  "Smooth finish at the corners",
  "Socket",
  "Soft Nylon Tube",
  "Solenoid Base",
  "Solenoid Valve",
  "Solenoid Valve Plate",
  "Soluble",
  "Soluble Piping Diagram",
  "Spacer",
  "Spacer Plate",
  "Special Note for Tube Protection using Silicon Varnish Glass",
  "Spherical Washer",
  "Spindle",
  "Spindle Head",
  "Spiral Bevel Gear",
  "Spiral Miter Gear",
  "Spline Shaft",
  "Split Collar",
  "Split Tube Coupling",
  "Spool Retainer",
  "Spool Shaft",
  "Spring",
  "Spring Board",
  "Spring Board Mounting Seat",
  "Spring Bolt",
  "Spring Case",
  "Spring pin hole",
  "Spring Plate",
  "Spring Rod",
  "Sprocket",
  "Sprocket Shaft",
  "Sprocket Support",
  "Spur Gear",
  "Square Pipe Skid",
  "Squeeze Stand",
  "Squeeze Stand Assy",
  "Stack Entry Side Conveyor Assy",
  "Stagger Welding",
  "Stand",
  "Standard Note for Hex Nut on Part",
  "Standard Separate Collar",
  "Standard Shaft",
  "Standard Welding Note",
  "Standard Welding Note (For Sir. Fujiyama)",
  "Standoff",
  "Static (Dynamic) Pressure Bearing",
  "Stay",
  "Steel Pipe",
  "Steel Revolving Grip",
  "Stepped Key",
  "Stepped Spacer",
  "Stop Nut",
  "Stop Plate Sets",
  "Stopper",
  "Stopper Arm",
  "Stopper Block",
  "Stopper Bolt",
  "Stopper Bracket",
  "Stopper Frame",
  "Stopper Fulcrum Shaft",
  "Stopper Head",
  "Stopper Mounting",
  "Stopper Plate",
  "Stopper Screw",
  "Stopper screw with splitting (Flat head)",
  "Stopper Screw With Urethane Pad",
  "Stopper Shaft",
  "Stopper Stand",
  "Stopper Support",
  "Storage Conveyor Assy",
  "Straight Elbow",
  "Strike",
  "Strut",
  "Stud Bolt",
  "STW",
  "Sub Base",
  "Sub Flange",
  "Sub Frame",
  "Super Liner Motor",
  "Support Frame",
  "Support Plate",
  "Support Roll",
  "Support Roll Axis",
  "Support Roller",
  "Support Roller Assy",
  "Support Unit",
  "Support Wheel Assy",
  "Suspender",
  "SW Run Out Table (Pinch Roll)",
  "SW Shear Welder",
  "SWER Shear Welder (Bed)",
  "SWER Shear Welder (Entry Guide Roll)",
  "Swing Bearing",
  "Switch Mounting Base",
  "Swivel Joint",
  "SWLW Shear Welder (Exit Support Roll)",
  "SWPR Shear Welder (Lower Blade & Clamp)",
  "SWPR Shear Welder (Pinch Roll)",
  "SWSR Shear Welder (Shear Cylinder)",
  "SWSR Shear Welder (Side Roll Stand)",
  "SWUP Shear Welder (Torch Feed Head)",
  "SWUP Shear Welder (Upper Blade & Side Clamp)",
  "Symmetry to this drawing",
  "Symmetry with this parts",
  "Synchro Belt",
  "Synchro Pulley",
  "Synchronize Gear",
  "SZ Roll Stand Assy",
  "T-Block",
  "T-Clamp",
  "T-Nut",
  "Tail end detector for pinch roll",
  "Tail end for kick out start",
  "Tap at assembly",
  "Tap Plate",
  "Tap Seat",
  "Taper pin(with tapping)",
  "Tapered Block",
  "Tapped Plate",
  "Tee",
  "Tempering work with 3 mm remaining Hardness HS35-40",
  "Tension Axis",
  "Tension Lever",
  "Tensioner",
  "Tensioner Angle",
  "Tensioner Bracket",
  "Tensioner Plate",
  "Terminal Box Installation Drawing",
  "TH Soluble Piping Diagram",
  "The area must not have welding bead",
  "The location must be accurate",
  "The location of holes must be accurately process to the teeth location as shown drawing",
  "The width dimension (10) is to be polished at the same time as SB55116N01",
  "Thickness for base 0.3mm(Shotblast)",
  "This surface has attachment during installation, and this cannot be painted",
  "Threaded Bar",
  "Threaded Bushing",
  "Through",
  "Throw Away Tip",
  "Thrust Holder",
  "Thrust Ring",
  "Tie Block",
  "Tie Plate",
  "Timing Belt",
  "Tip Bracket",
  "Tip Holder",
  "Tip Sheet",
  "Tool Holder",
  "Tool Shaft",
  "Top Bracket",
  "Top Cover",
  "Top Cutter Assy",
  "Top Cutter Lifting",
  "Top Cutter Rotating",
  "Top End Plate",
  "Top Frame",
  "Top Guide",
  "Top Holder",
  "Top Limit SW Dwg.",
  "Top Plate",
  "Top Roll",
  "Top Roll Base Assy",
  "Top Roll Drive Assy",
  "Top Roll Instl. Dwg.",
  "Top Roll Pin",
  "Top Roll Stand",
  "Top Roll Turning",
  "Top Roll Up/Down Assy",
  "Top Roll Yoke Assy",
  "Top Roller",
  "Top Shoe",
  "Torch Feed Head Assy",
  "Torch Stand",
  "Torque Arm",
  "Torque Nut",
  "Torque Plate",
  "Torque Plate Bracket",
  "TRAI Tightening Exit side (Roller Table)",
  "TRAI Transfer Table (Conveyor)",
  "TRAL Transfer Machine (Walking Unit)",
  "TRAL Transfer Table (Air Blow Device)",
  "TRAL Transfer Table (Alignment)",
  "Transport Frame",
  "Transport Gearbox Assy",
  "Trapezoidal Screw",
  "Trapezoidal Screw Nut",
  "Traveling Base",
  "Traveling Beam",
  "Traveling Drive Unit Assy",
  "TRCV Transfer Table (Lifter)",
  "Trestle",
  "TRHT Uncoiler (Coil End Clamp)",
  "Trim",
  "TRPG Uncoiler (Coil End Clamp)",
  "TRPV Transfer Table (Pull Out Conveyor)",
  "TRPV Transfer Table (Rack)",
  "TRPV Transfer Table (Roller Table)",
  "TRPV Transfer Table (Walking Unit)",
  "TRTK Uncoiler (Coil End Clamp)",
  "TRWK Transfer Table (Air Blow Device)",
  "TRWK Traveling Shear (Carriage Device)",
  "TRWK Turning Machine",
  "TRWK Uncoiler",
  "TRWK Uncoiler (Brake Unit)",
  "TSCA Uncoiler (Coil End Clamp)",
  "TSCA Uncoiler (Main Frame)",
  "TSP Coupler Socket",
  "Tube Mill",
  "Turn Table",
  "Turning Assy",
  "Turning Lock Assy",
  "U Bolt",
  "U Nut",
  "UCMD Uncoiler (Mandrel)",
  "UCMD Uncoiler (Out Fitting)",
  "UCTN Uncoiler (Support Roll Device)",
  "UCTN Uncoiler (Turning Device)",
  "UJ Clamp Intermediate Base",
  "Union",
  "Unit Stopper Assy",
  "Universal Joint",
  "Universal Support Assy",
  "Upper & Lower Device Assy",
  "Upper & Lower Tool",
  "Upper Blade",
  "Upper Blade Block",
  "Upper Body Frame (Fixed Side)",
  "Upper Body Frame (Moving Side)",
  "Upper Bracket",
  "Upper Chock (W.S)",
  "Upper Chuck Holder",
  "Upper Frame",
  "Upper Guide",
  "Upper Tool & Side Clamp Assy",
  "Urethane",
  "Urethane coating process",
  "Urethane Collar",
  "Urethane Sheet",
  "Urethane Skid",
  "Urethane Stopper",
  "Valve Bracket",
  "Valve Stand Mount",
  "VP call 50",
  "WABC Welding Apparatus (Bead Chopper)",
  "WABC Welding Apparatus (Bead Cutter)",
  "WABH Welding Apparatus (Bead Winder)",
  "WABH Welding Apparatus (Chopper Inner Bead cutter)",
  "Warn",
  "Washer",
  "Water Coolant Piping System",
  "Wear Plate",
  "Wear Ring",
  "Wedge Liner",
  "Weight",
  "Weld at assembly",
  "Weld Plate",
  "Weld Seat",
  "Weld without any leakage due to Oil Pan",
  "Welded part has a smooth G finish",
  "Wheel",
  "Wheel Axis",
  "Wheel Axle",
  "Wheel Brush",
  "Wheel Frame",
  "Wheel Plate",
  "Wheel Shaft",
  "Wheels",
  "Whirlstop",
  "White",
  "Wind Jet Blow-Off Nozzle",
  "Window Frame",
  "Wiper",
  "Wonder Gun",
  "Wood",
  "Work Guide",
  "Work Process",
  "Work Side",
  "Worm",
  "Worm Gear Jack",
  "Worm Jack",
  "Worm Nut",
  "Worm Screw (Left)",
  "Worm Screw (Right)",
  "Worm Shaft",
  "Y-Type Double Knuckle Joint",
  "Yoke Guide",
  "※Mark area must have center scribe line",
  "※symbol area and range",
  "· Consider safety for the cut surfaces above and below the expanded metal",
  "· Expanded metal is painted black",
  "· The surface of The expanded metal (without burrs) is used as The surface in this figure"
];

export const FILE_CATEGORIES = [
  "Purchase Parts",
  "Projects"
];
